version: '3.9'
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: xxx_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  bff:
    build:
      context: ../services/bff
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/xxx_app
      JWT_ACCESS_SECRET: dev-access-secret
      JWT_REFRESH_SECRET: dev-refresh-secret
      ID_TOKEN_SHARED_SECRET: dev-oidc-secret
      TOKEN_TTL_SECONDS: 900
      REFRESH_TOKEN_TTL_SECONDS: 2592000
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX_REQUESTS: 30
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
