include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-raw-types: false
    strict-inference: true
linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_final_locals: true
